### ISSUE TITLE
Ayakas skin dress material fx isnt working.

### ISSUE THREAD

**Issue by maxm1lk** [Manashiku/MMDGenshin#9]
![image](https://github.com/Manashiku/MMDGenshin/assets/148462659/ace2b17f-638a-4ac6-9b63-3d631e74b84a) Its always gives me this error message...

**Comment by Manashiku** [comment]
I have a few questions: 

1. Did you manually set up the material or did you use the pmx plugin? 
2. If you used the plugin, what kind of json are you feeding it?

The error is caused by the ALPHA_CUTOFF variable not being declared which is either caused by the line having been deleted or the line was never written by the plugin. Depending on what method your material fx was created.

**Comment by maxm1lk** [comment]
I used material generator from 1.1.7 shader release to create a .fx file and used the json file from zeroruka repo....I just didnt noticed that its missing this value....
